### ISSUE TITLE
Question about file organization

### ISSUE THREAD

**Issue by cahlan** [Glathrop/referenceList#7]
Curious why you chose to put controllers inside of the partials directory.

**Comment by Glathrop** [comment]
The partials are organized by view and my thinking was it would be convenient to have the controller for that view located in the same folder for easy access. Please let me know it this is non-standard or if there is a better way.

**Comment by cahlan** [comment]
There isn't really a standard per se, but typically the word "partials" is used for markup (HTML) files only. You don't typically see Javascript in a partials folder.

**Comment by Glathrop** [comment]
Ok good to know. I'll adjust accordingly.
