### ISSUE TITLE
Indendation

### ISSUE THREAD

**Issue by cahlan** [Glathrop/referenceList#8]
Indentation is a minor thing ... it doesn't affect functionality. What it does affect, however, is readibility. Whether you're showing code to an employer or handing it off to another team member, readibility is very important. Correcting your indentation (see [referenceService.js](https://github.com/Glathrop/referenceList/blob/gh-pages/partials/references/referenceService.js), for example) will just help your code show cleaner and more readible.

I'm not sure what your IDE is, but with SublimeText, I found [this package](http://stackoverflow.com/a/12867043/1160485) very useful.

**Comment by Glathrop** [comment]
I'll pay closer attention to this before the next submission. I am on Atom and have a good package to help with this.
